Repository Torchlight-SWE2324/Documentazione, pull requests merged in 2023-11, with the labels that each got.

#8 [TCHL-8] Miglioramenti organizzativi
  1 - Candidatura/Verbali/verbale_esterno_23_10_2023.pdf
  1 - Candidatura/lettera_presentazione_v1_0.pdf
  1 - Candidatura/preventivo_impegni_v1_0.pdf
  1 - Candidatura/valutazione_capitolati_v1_0.pdf
  README.md
  rsc/docs_dark.svg
  rsc/docs_light.svg
Labels: documentation, enhancement

#9 [TCHL-9] Cambio formato data e verbale del 06/11
  1 - Candidatura/Verbali/Verbali interni/verbale_2023_10_16.pdf
  1 - Candidatura/Verbali/Verbali interni/verbale_2023_10_17.pdf
  1 - Candidatura/Verbali/Verbali interni/verbale_2023_10_20.pdf
  1 - Candidatura/Verbali/Verbali interni/verbale_2023_10_21.pdf
  1 - Candidatura/Verbali/Verbali interni/verbale_2023_10_28.pdf
  1 - Candidatura/Verbali/verbale_esterno_2023_10_23.pdf
  2 - RTB/Verbali/Verbali interni/verbale_2023_11_06.pdf
  README.md
Labels: documentation, enhancement

#11 - Aggiornata la sezione della candidatura
  README.md
Labels: enhancement

#12 [TCHL-12] Corretto il link nel README
  README.md
Labels: bug

#13 [TCHL-9] Aggiunta verbale del 11 Novembre
  2 - RTB/Verbali/Verbali interni/verbale_2023_11_11.pdf
Labels: documentation

#14 [TCHL-14] Aggiunto il link all verbale interno
  README.md
Labels: documentation, enhancement

#15 [TCHL-16] Quickfix al verbale interno
  2 - RTB/Verbali/Verbali interni/verbale_2023_11_11.pdf
Labels: documentation, enhancement

#16 [TCHL-18] Aggiunta del verbale esterno controfirmato
  2 - RTB/Verbali/Verbali esterni/varbale_esterno_2023_11_13.pdf
  README.md
Labels: documentation

#17 [TCHL-18] Correzione al nome del file
  2 - RTB/Verbali/Verbali esterni/verbale_esterno_2023_11_13.pdf
Labels: documentation

#18 [TCHL-24] Aggiunto verbale del 18 Novembre
  2 - RTB/Verbali/Verbali interni/verbale_2023_11_18.pdf
  README.md
Labels: documentation

#19 [TCHL-26] Aggiornati i verbali
  2 - RTB/Verbali/Verbali interni/verbale_2023_11_06.pdf
  2 - RTB/Verbali/Verbali interni/verbale_2023_11_11.pdf
  2 - RTB/Verbali/Verbali interni/verbale_2023_11_18.pdf
Labels: documentation, enhancement

#20 [TCHL-31] Aggiunta verbale del 25/11 e relativo link nel README
  2 - RTB/Verbali/Verbali interni/verbale_2023_11_25.pdf
  README.md
Labels: documentation

#21 [TCHL-32] Miglioramenti alla struttura della cartella RTB
  2 - RTB/Documentazione Esterna/Verbali Esterni/verbale_esterno_2023_11_13.pdf
  2 - RTB/Documentazione Esterna/analisi_requisiti.txt
  2 - RTB/Documentazione Esterna/glossario.txt
  2 - RTB/Documentazione Esterna/piano_progetto.txt
  2 - RTB/Documentazione Esterna/piano_qualifica.txt
  2 - RTB/Documentazione Interna/Verbali Interni/verbale_2023_11_06.pdf
  2 - RTB/Documentazione Interna/Verbali Interni/verbale_2023_11_11.pdf
  2 - RTB/Documentazione Interna/Verbali Interni/verbale_2023_11_18.pdf
  2 - RTB/Documentazione Interna/Verbali Interni/verbale_2023_11_25.pdf
  2 - RTB/Documentazione Interna/norma_progetto.txt
  2 - RTB/lettera_presentazione.txt
Labels: documentation, enhancement
